package com.sistema.pedido.model;

public enum EstadoPedido {
	PENDIENTE_CONFIRMACION,
	PENDIENTE_STOCK,
	PENDIENTE_PREPARACION,
	PENDIENTE_ENTREGA,
	EN_VIAJE,
	ENTREGADO,
	ENTREGADO_PARCIAL,
	RE_AGENDADO,
	RECHAZADO
}
